---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: ['bundle/require']
domains: []
reporters:
- require_not_found
- typecheck:typed
require_paths: []
max_files: 5000
